title:              oreum
email:              chaoreum0525@gmail.com
description:        Want to know about this man
author:             waterspouut
baseurl:            "/want-to-know-about-this-man"
url:                "https://waterspouut.github.io/"

# Social Profiles
twitter_username:   
github_username:    waterspouut
facebook_username:  
instagram_username:  waterspouut
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   GTM-K9LRVK3S # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
